// Shared corpus of Markdown inputs covering the Luogu extended syntax surface.
// Used for both the snapshot baseline and the assertion suite.
module.exports = [
  ['basic-emphasis', '**粗体** *斜体* ***粗斜体*** ~~删除线~~ `code`'],
  ['headings', '# H1\n## H2\n### H3\n#### H4'],
  ['hardbreak-spaces', '第一行  \n第二行'],
  ['hardbreak-backslash', '第一行\\\n第二行'],
  ['escapes', 'a\\*b\\_c\\`d\\$e\\[f\\]g'],
  ['paragraph-join', '一句话\n继续同一段\n\n新段落'],

  ['inline-math', '设 $x^2 + y^2 = z^2$ 成立。'],
  ['display-math', '$$\\sum_{i=1}^n \\frac{1}{i}$$'],
  ['math-multiline', '$$\n\\begin{aligned}\na &= b \\\\\nc &= d\n\\end{aligned}\n$$'],
  ['math-many', Array.from({ length: 30 }, (_, i) => `第 ${i} 段 $a_{${i}}$ 与 $$b_{${i}}$$`).join('\n\n')],
  ['math-cjk-reject', '花费$5和$10 元'],
  // CJK inside a formula must still render: Luogu accepts it, and rejecting every
  // span containing CJK also killed valid formulas like $设x=1$ and $a_{最大}$.
  ['math-cjk-inline-accept', '行内 $设x=1$ 与 $a_{最大}$ 都是公式'],
  ['math-cjk-display', '$$设 x = 1$$'],
  ['math-cjk-display-multiline', '$$\n\\begin{aligned}\na &= b \\\\\nc &= 中文说明\n\\end{aligned}\n$$'],
  ['math-cjk-text-wrapped', '$$\\text{设有} n \\text{个点}$$'],
  ['math-cjk-prose-reject', '价格是$100，另一个是$200'],
  ['math-in-code', '`$x$` 不该被解析\n\n```\n$y$\n```'],
  ['math-adjacent', '$a$$b$'],
  ['math-empty', '$$ $$'],

  ['code-plain', '```\nint main(){return 0;}\n```'],
  ['code-cpp', '```cpp\n#include <iostream>\nint main(){ std::cout << 1; }\n```'],
  ['code-linenumbers', '```cpp line-numbers\nint a = 1;\nint b = 2;\n```'],
  ['code-highlight-range', '```cpp line-numbers lines=1-2\nint a;\nint b;\nint c;\n```'],
  ['code-highlight-list', '```cpp lines=1,3\nint a;\nint b;\nint c;\n```'],
  ['code-tilde', '~~~python\nprint(1)\n~~~'],

  ['table-simple', '| a | b |\n| --- | --- |\n| 1 | 2 |'],
  ['table-align', '| l | c | r |\n| :-- | :-: | --: |\n| 1 | 2 | 3 |'],
  ['table-rowspan', '| a | b |\n| --- | --- |\n| 1 | 2 |\n| ^ | 3 |'],
  ['table-colspan', '| a | b |\n| --- | --- |\n| 1 | < |'],
  ['table-mixed', '| a | b | c |\n| --- | --- | --- |\n| 1 | 2 | 3 |\n| ^ | < | 4 |'],
  ['table-cute', '::cute-table{tuack}\n\n| a | b |\n| --- | --- |\n| 1 | 2 |'],

  ['callout-info', ':::info\n内容\n:::'],
  ['callout-open', ':::success{open}\n内容\n:::'],
  ['callout-warning', ':::warning\n注意\n:::'],
  ['callout-error', ':::error\n错误\n:::'],
  ['callout-title-math', '::::success[$$\\gcd(i,j)$$]\n内容\n::::'],
  ['callout-nested', '::::info\n外层\n\n:::warning\n内层\n:::\n\n::::'],
  ['epigraph', ':::epigraph[鲁迅]\n我没说过这句话。\n:::'],
  ['align-center', ':::align{center}\n居中文字\n:::'],
  ['align-right', ':::align{right}\n居右文字\n:::'],

  ['list-ul', '- a\n- b\n- c'],
  ['list-ol', '1. a\n2. b'],
  ['list-nested', '- a\n  - b\n    - c'],
  ['list-task', '- [ ] todo\n- [x] done'],
  ['blockquote', '> 引用\n> 第二行'],
  ['hr', '---'],

  ['link', '[洛谷](https://www.luogu.com.cn)'],
  ['link-title', '[洛谷](https://www.luogu.com.cn "首页")'],
  ['autolink', '<https://www.luogu.com.cn>'],
  ['image', '![alt](https://cdn.luogu.com.cn/x.png)'],
  ['image-title', '![alt](https://cdn.luogu.com.cn/x.png "标题")'],
  ['bilibili-bv', '![](bilibili:BV1xx411c7mD)'],
  ['bilibili-av', '![](bilibili:av170001)'],

  // Security-relevant inputs (behaviour asserted separately).
  ['xss-img-onerror', '<img src=x onerror=alert(1)>'],
  ['xss-script', '<script>alert(1)</script>'],
  ['xss-js-link', '[x](javascript:alert(1))'],
  ['xss-js-image', '![a](javascript:alert(1))'],
  ['xss-svg-onload', '<svg onload=alert(1)>'],
  ['xss-data-uri', '[x](data:text/html,<script>alert(1)</script>)'],
  ['xss-vbscript', '[x](vbscript:msgbox(1))'],
  ['xss-mixed-case', '[x](JaVaScRiPt:alert(1))'],
  ['xss-tab-obfuscated', '[x](java\tscript:alert(1))'],
  ['html-in-code', '```html\n<img src=x onerror=alert(1)>\n```'],
  ['html-inline-code', '`<b>not bold</b>`'],
  ['safe-relative-link', '[x](/problem/P1001)'],
  ['safe-anchor', '[x](#section)'],
  ['safe-mailto', '[x](mailto:a@b.com)'],

  ['mixed-doc', [
    '# 题解 P1001',
    '',
    '## 思路',
    '',
    '考虑 $O(n\\log n)$ 做法，设 $f_i$ 表示前 $i$ 个数。',
    '',
    '$$f_i = \\max_{j<i}\\{f_j + a_i\\}$$',
    '',
    ':::info{open}',
    '注意边界 $i=0$。',
    ':::',
    '',
    '| 数据 | 范围 |',
    '| :-: | :-: |',
    '| $n$ | $10^5$ |',
    '| ^ | < |',
    '',
    '```cpp line-numbers lines=2',
    '#include <bits/stdc++.h>',
    'int main(){ return 0; }',
    '```',
    '',
    '> 参考 [OI Wiki](https://oi-wiki.org)',
  ].join('\n')],
];
